# Perceptron en Python
Forma más simple:

tenemos 


$output = inputs * weights  + b$

In [2]:
inputs = [1,2,3,4]
weights = [-0.5, 2, 1, -1.3]
b = 0

In [3]:
output = sum([input * weight for input, weight in zip(inputs, weights)]) + b
output

1.2999999999999998

Haciéndolo de manera más general y convirtiendo $weights$ en un matriz, obtenemos la siguiente función que sirve genéricamente

In [4]:
def layer_calculation(inputs, weights, bias):
    # Outputs finales
    outputs = []

    # Iteramos sobre inputs y bias
    for weight_vector, n_bias in zip(weights, bias):
        # valor de cada entrada de neurona
        output_neuron = 0
        for n_input, weight_value in zip(inputs, weight_vector):
            # Sumar cada componente
            output_neuron += n_input * weight_value
        # añadir bias
        outputs.append(output_neuron + n_bias)
        
    return outputs


In [5]:
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
    ]
biases = [2, 3, 0.5]

In [6]:
print(layer_calculation(inputs, weights, biases))

[4.8, 1.21, 2.385]


## Numpy
Con numpy se puede hacer de manera expedita, dado que tenemos el producto punto.

Una nuerona sería

In [7]:
import numpy as np

In [8]:
inputs = [1,2,3,4]
weights = [-0.5, 2, 1, -1.3]
b = 0

output = np.dot(weights, inputs) + b
output

np.float64(1.2999999999999998)

De manera similar podemos ahorrar tiempo a la hora de tener una capa con múltiples perceptrones

In [9]:
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
    ]
biases = [2, 3, 0.5]

outputs = np.dot(weights, inputs) + biases
outputs

array([4.8  , 1.21 , 2.385])

De manera similar, podemos tomar batches(grupos de inputs), que son útiles en 
esta situaciones, dado que estabiliza la manera en la que se comporta el cambio
de nuestra función a la hora de ser entrenada y aumenta la velocidad en la que
es posible entrenar el modelo.

In [14]:
inputs = np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])

weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])

biases = np.array([2,3,0.5])

In [17]:
output = np.dot(inputs, weights.T) + biases
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

## Capas ocultas
Las capas ocultas no son más que agarrar la capa de atrás y usarla para
generar una nueva capa, que naturalmente usará estos valores como inputs,
y necesitará un nuevo conjunto de pesos y de bias. 

In [ ]:
inputs = np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])

weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])

biases = np.array([2,3,0.5])

weights2 = np.array([
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [0.44,0.73,-0.13],
])

biases2 = np.array([-1,2,-0.5])

# calculamos la capa inicial
layer1_output = np.dot(inputs, weights.T) + biases
# Calculamos la capa oculta usando la salida de la capa anterior
layer2_output = np.dot(layer1_output, weights2.T) + biases2
layer2_output

array([[ 0.5031 , -1.04185,  2.18525],
       [ 0.2434 , -2.7332 ,  2.0687 ],
       [-0.99314,  1.41254,  0.88425]])